self install is working now

diff --git a/bin/bob b/bin/bob
--- a/bin/bob
+++ b/bin/bob
@@ -1,47 +1,24 @@
 #!/bin/sh
 
-export BOB_VERSION="0.0.1"
+export BOB_VERSION="0.0.1-SNAPSHOT"
 
 case $BOB_VERSION in
     *SNAPSHOT) SNAPSHOT="YES" ;;
     *) SNAPSHOT="NO" ;;
 esac
 
-# Make sure classpath is in unix format for manipulating, then put
-# it back to windows format when we use it
-if [ "$OSTYPE" = "cygwin" ] && [ $CLASSPATH != "" ]; then
-    CLASSPATH=`cygpath -up $CLASSPATH`
-fi
-
-if [ $USER = "root" ] && [ "$BOB_ROOT" = "" ]; then
-    echo "WARNING: You're currently running as root; probably by accident."
-    echo "Press control-C to abort or Enter to continue as root."
-    echo "Set BOB_ROOT to disable this warning."
-    read
-fi
-
 ORIGINAL_PWD="$PWD"
-while [ ! -r "$PWD/bob.clj" ] && [ "$PWD" != "/" ] && [ ! $NOT_FOUND ]
-do
-    cd ..
-    if [ "$(dirname "$PWD")" = "/" ]; then
-        NOT_FOUND=0
-        cd "$ORIGINAL_PWD"
-    fi
-done
 
 if [ "$BOB_HOME" = "" ]; then
     BOB_HOME="$HOME/.bob"
 fi
 
-BOB_PLUGINS="$(ls -1 lib/dev/*jar 2> /dev/null | tr \\n \:)"
-BOB_USER_PLUGINS="$(ls -1 $BOB_HOME/plugins/*jar 2> /dev/null | tr \\n \:)"
-CLASSPATH=$BOB_USER_PLUGINS:$BOB_PLUGINS:src/:$CLASSPATH
-BOB_JAR="$HOME/.m2/repository/cl-bob/clj-bob/$BOB_VERSION/clj-bob-$BOB_VERSION-standalone.jar"
-CLOJURE_JAR="$HOME/.m2/repository/org/clojure/clojure/1.2.0/clojure-1.2.0.jar"
+BOB_PACKAGES="$(ls -1 $BOB_HOME/packages/*jar 2> /dev/null | tr \\n \:)"
+CLASSPATH=$BOB_PACKAGES::$CLASSPATH
+BOB_JAR="$HOME/.bob/self-installs/bob-$BOB_VERSION-standalone.jar"
+
 NULL_DEVICE=/dev/null
 
-# normalize $0 on certain BSDs
 if [ "$(dirname "$0")" = "." ]; then
     SCRIPT="$(which $(basename "$0"))"
 else
@@ -61,12 +38,26 @@ done
 
 BIN_DIR="$(dirname "$SCRIPT")"
 
-# Not running from a checkout
-CLASSPATH="$BOB_JAR:$CLASSPATH"
+if [ -r "$BIN_DIR/../src/bob/core.clj" ]; then
+    echo "Running from local directory"
+    # Running from source checkout
+    BOB_DIR="$(dirname "$BIN_DIR")"
+    BOB_LIBS="$(find -H $BOB_DIR/lib -mindepth 2> /dev/null 1 -maxdepth 1 -print0 | tr \\0 \:)"
+    CLASSPATH="$BOB_DIR/src:$BOB_DIR/resources:$BOB_LIBS:$CLASSPATH:$BOB_JAR"
 
-if [ ! -r "$BOB_JAR" -a "$1" != "self-install" ]; then
-    "$0" self-install
+    if [ "$BOB_LIBS" = "" -a "$1" != "self-install" -a ! -r "$BOB_JAR" ]; then
+        echo "Clj-Bob is missing its dependencies. Please see \"Building\" in the README."
+        exit 1
+    fi
+else
+    # Not running from a checkout
+    CLASSPATH="$BOB_JAR:$CLASSPATH"
+
+    if [ ! -r "$BOB_JAR" -a "$1" != "self-install" ]; then
+        "$0" self-install
+    fi
 fi
+
 
 HTTP_CLIENT="wget -O"
 if type -p curl >/dev/null 2>&1; then
@@ -81,7 +72,7 @@ if [ "$1" = "self-install" ]; then
     echo "Downloading Bob  now..."
     BOB_DIR=`dirname "$BOB_JAR"`
     mkdir -p "$BOB_DIR"
-    BOB_URL="http://github.com/downloads/sivajag/clj-bob/clj-bob-$BOB_VERSION-standalone.jar"
+    BOB_URL="https://github.com/downloads/sivajag/clj-bob/bob-$BOB_VERSION-standalone.jar"
     $HTTP_CLIENT "$BOB_JAR" "$BOB_URL"
     if [ $? != 0 ]; then
         echo "Failed to download $BOB_URL"
@@ -137,7 +128,7 @@ else
     # TODO: add more to the boot classpath
     test $CYGWIN_JLINE && stty -icanon min 1 -echo
     exec $RLWRAP $JAVA_CMD -Xbootclasspath/a:"$CLOJURE_JAR" -client $JAVA_OPTS \
-        -cp "$CLASSPATH" $JLINE clojure.main -e "(use 'com.sivajag.clj-bob.core)(-main)" \
+        -cp "$CLASSPATH" $JLINE clojure.main -e "(use 'bob.core)(-main)" \
         $NULL_DEVICE $@
     test $CYGWIN_JLINE && stty icanon echo
 fi
